#!/bin/sh
set -e
if [ "$1" = "remove" ] && command -v systemctl >/dev/null 2>&1; then
  systemctl stop audiobookshelf.service >/dev/null 2>&1 || true
  systemctl disable audiobookshelf.service >/dev/null 2>&1 || true
fi
exit 0
